/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktualneRouteImport } from './routes/aktualne'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as HistorieRouteImport } from './routes/historie'
import { Route as OProjektuRouteImport } from './routes/o-projektu'
import { Route as PrispetRouteImport } from './routes/prispet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as PribehyIndexRouteImport } from './routes/pribehy.index'
import { Route as PribehySlugRouteImport } from './routes/pribehy.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktualneRoute = AktualneRouteImport.update({
  id: '/aktualne',
  path: '/aktualne',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorieRoute = HistorieRouteImport.update({
  id: '/historie',
  path: '/historie',
  getParentRoute: () => rootRouteImport,
} as any)
const OProjektuRoute = OProjektuRouteImport.update({
  id: '/o-projektu',
  path: '/o-projektu',
  getParentRoute: () => rootRouteImport,
} as any)
const PrispetRoute = PrispetRouteImport.update({
  id: '/prispet',
  path: '/prispet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PribehyIndexRoute = PribehyIndexRouteImport.update({
  id: '/pribehy/',
  path: '/pribehy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PribehySlugRoute = PribehySlugRouteImport.update({
  id: '/pribehy/$slug',
  path: '/pribehy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktualne': typeof AktualneRoute
  '/galerie': typeof GalerieRoute
  '/historie': typeof HistorieRoute
  '/o-projektu': typeof OProjektuRoute
  '/prispet': typeof PrispetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/pribehy/$slug': typeof PribehySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/pribehy/': typeof PribehyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktualne': typeof AktualneRoute
  '/galerie': typeof GalerieRoute
  '/historie': typeof HistorieRoute
  '/o-projektu': typeof OProjektuRoute
  '/prispet': typeof PrispetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/pribehy/$slug': typeof PribehySlugRoute
  '/admin': typeof AdminIndexRoute
  '/pribehy': typeof PribehyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktualne': typeof AktualneRoute
  '/galerie': typeof GalerieRoute
  '/historie': typeof HistorieRoute
  '/o-projektu': typeof OProjektuRoute
  '/prispet': typeof PrispetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/pribehy/$slug': typeof PribehySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/pribehy/': typeof PribehyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktualne'
    | '/galerie'
    | '/historie'
    | '/o-projektu'
    | '/prispet'
    | '/sitemap.xml'
    | '/admin/login'
    | '/pribehy/$slug'
    | '/admin/'
    | '/pribehy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktualne'
    | '/galerie'
    | '/historie'
    | '/o-projektu'
    | '/prispet'
    | '/sitemap.xml'
    | '/admin/login'
    | '/pribehy/$slug'
    | '/admin'
    | '/pribehy'
  id:
    | '__root__'
    | '/'
    | '/aktualne'
    | '/galerie'
    | '/historie'
    | '/o-projektu'
    | '/prispet'
    | '/sitemap.xml'
    | '/admin/login'
    | '/pribehy/$slug'
    | '/admin/'
    | '/pribehy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktualneRoute: typeof AktualneRoute
  GalerieRoute: typeof GalerieRoute
  HistorieRoute: typeof HistorieRoute
  OProjektuRoute: typeof OProjektuRoute
  PrispetRoute: typeof PrispetRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  PribehySlugRoute: typeof PribehySlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PribehyIndexRoute: typeof PribehyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktualne': {
      id: '/aktualne'
      path: '/aktualne'
      fullPath: '/aktualne'
      preLoaderRoute: typeof AktualneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historie': {
      id: '/historie'
      path: '/historie'
      fullPath: '/historie'
      preLoaderRoute: typeof HistorieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-projektu': {
      id: '/o-projektu'
      path: '/o-projektu'
      fullPath: '/o-projektu'
      preLoaderRoute: typeof OProjektuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prispet': {
      id: '/prispet'
      path: '/prispet'
      fullPath: '/prispet'
      preLoaderRoute: typeof PrispetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pribehy/': {
      id: '/pribehy/'
      path: '/pribehy'
      fullPath: '/pribehy/'
      preLoaderRoute: typeof PribehyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pribehy/$slug': {
      id: '/pribehy/$slug'
      path: '/pribehy/$slug'
      fullPath: '/pribehy/$slug'
      preLoaderRoute: typeof PribehySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktualneRoute: AktualneRoute,
  GalerieRoute: GalerieRoute,
  HistorieRoute: HistorieRoute,
  OProjektuRoute: OProjektuRoute,
  PrispetRoute: PrispetRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  PribehySlugRoute: PribehySlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PribehyIndexRoute: PribehyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
